### ISSUE TITLE
file name conflict in vue case

### ISSUE THREAD

**Issue by caijiehong** [samonxian/vite-plugin-build#15]
my project files like this
```
src/index.ts
src/index.vue
```

src/index.ts like this
```ts
import page from './index.vue'
export { page }
```

vite.config.ts like this
```ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { buildPlugin } from 'vite-plugin-build';


export default defineConfig({
  plugins: [
    buildPlugin(
      {
        fileBuild: {
          emitDeclaration: true,
          isVue: true,
          esOutputDir: 'dist',
          commonJsOutputDir: false,
        }
      }
    ),
    vue(),
  ],
});

```

while `vite-plugin-build` would transfer like this
 `src/index.ts` => `dist/index.js` and `dist/index.d.ts`
 `src/index.vue` => `dist/index.js` and `dist/index.d.ts`
 
 so the conflict happened.

**Comment by samonxian** [comment]
It is the right action, `file.js`,`file.ts`,`file.tsx`,`file.vue` and `file.sevlte` all will convert to `file.js`, the same as  the  created dts file.
You should rename the file.

**Comment by caijiehong** [comment]
@samonxian 
But such file names was allow by vue framework，and it works just fine in `vue-tsc` ，`vite`

**Comment by caijiehong** [comment]
can we convert `file.vue` to `file.vue.js`
just like `vue-tsc` convert `file.vue` to `fle.vue.d.ts`

**Comment by samonxian** [comment]
@caijiehong Mabe that's the better way, i will suppot it next time.
