### ISSUE TITLE
0.10.0 版本 emitDeclaration 无效

### ISSUE THREAD

**Issue by Darcrandex** [samonxian/vite-plugin-build#16]
emitDeclaration: true 没有生成声明文件

demo
https://stackblitz.com/edit/vitejs-vite-ncrgpz?file=dist%2Frbac-components.es.js

**Comment by samonxian** [comment]
tsconfig.json 配置有问题，目前 noEmit 配置为 true，就不会有声明文件生成
后续得加上强制 emit 才行。
