### ISSUE TITLE
Can not import

### ISSUE THREAD

**Issue by linxiaowu66** [samonxian/vite-plugin-build#2]
用这个编译完组件库之后无法import；

使用lib目录下的报export undefined
使用es目录下的报 module undefiened

所以这个插件打包后的文件怎么使用呢？

**Comment by samonxian** [comment]
你得描述具体点，你是怎么 import，然后报了什么错。

**Comment by samonxian** [comment]
可以看下这里，或许有帮助，你可能需要理解 common 和 es 的区别，还有 pacakge.json main 和 module 字段的用法
https://github.com/vitejs/vite/issues/813
