### ISSUE TITLE
watch mode doesn't work 

### ISSUE THREAD

**Issue by sebas0811buitrago** [samonxian/vite-plugin-build#3]
if I run `npx vite build --watch`  it just build one time and doesn't wait for changes to recompile again, but without the plugin it works well.

**Comment by samonxian** [comment]
It is not support cli watch mode, you can use vite config file to use watch mode and but watch mode is not support for emitting typescript declaration file. 

The watch mode setting is the same as [vite](https://vitejs.dev/config/build-options.html#build-watch) watch mode.

```ts
export default defineConfig({
  plugins: [
    buildPlugin({
      fileBuild: {
        emitDeclaration: true,
        watch: {},
      },
    }),
  ],
});

```

**Comment by truepatch** [comment]
@sebas0811buitrago You can use a crutch in vite.config.js

```js
const watch = process.argv.join().includes('--watch')
  ? {
      include: ['src/**'],
    }
  : null;

console.log(watch);

export default defineConfig({
  plugins: [
    buildPlugin({
      fileBuild: {
        emitDeclaration: true,
        watch
      },
    }),
  ],
});


```
