### ISSUE TITLE
json 文件不会打包进去

### ISSUE THREAD

**Issue by haiting** [samonxian/vite-plugin-build#6]
文件夹下有个 **test.json** 的文件，执行 pnpm run build 打包文件，**test.json** 文件没有一起打包进去

**Comment by samonxian** [comment]
这个是不支持的，只支持 ts、js 文件的转换，json 是不用转的，得自己写代码 copy 过去，Vite 有相关的复制插件可以用的。

**Comment by samonxian** [comment]
0.7.0 版本已支持
