### ISSUE TITLE
Issue with latest release 0.6.1

### ISSUE THREAD

**Issue by olmesm** [samonxian/vite-plugin-build#7]
I see you have released a new update on npm which has subsequently broken the build

`npm i vite-plugin-build@0.6.1` is broken

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for svelte-tsc@^0.6.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

`npm i vite-plugin-build@0.6.0` works

The fix is to release an update to your other package on npm https://www.npmjs.com/package/svelte-tsc => 0.6.1

Another improvement could be to add svelte-tsc as an [optional dependency](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies) or as a [bundled dependency](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies)

If you would like help setting up github actions to deploy this repo automatically to npm - please let me know! I'm happy to contribute. 

Thanks for the package! <3

**Comment by samonxian** [comment]
fixed, fogot to publish `svelte-tsc@^0.6.1`
