### ISSUE TITLE
不支持scss？

### ISSUE THREAD

**Issue by chenxin9482** [samonxian/vite-plugin-build#9]
我将 `vue-ts` clone下来一份，然后执行 `npm i sass`，接着将`less`修改成`scss`，最后执行`npm run build`
没有生成对应CSS文件，打包出来index.js的css引用是这样的
```
import style0 from "xxx/src/a/index.vue?used&vue&type=style&index=0&lang.module.scss";
```
sass是需要额外的什么配置么？

**Comment by samonxian** [comment]
之前的没有支持 vue 的 scss，0.7.1 版本支持了
